---
apiVersion: v1
kind: Service
metadata:
  namespace: php-service
  name: php-service
spec:
  type: NodePort
  selector:
    app: php-service
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30080
