---
k3s_state: installed
k3s_air_gap_installation: false
k3s_air_gap_files_dest_dir: /tmp/k3s-airgap/

k3s_air_gap_files_src_dir: "{{ playbook_dir }}/files/k3s/"
k3s_air_gap_extra_images_src_dir: "{{ playbook_dir }}/files/extra-images/"

k3s_air_gap_extra_images: []

k3s_server_manifests_templates: []

k3s_release_version: v1.20.5+k3s1

k3s_server:
  cluster-cidr: "10.42.0.0/16"
  kube-controller-manager-arg:
    - "pod-eviction-timeout=2m"
    - "node-monitor-grace-period=30s"
  https-listen-port: 6443
  flannel-backend: 'host-gw'
  disable:
    - traefik
    - servicelb

k3s_agent:
  node-label:
    - "worker=node1"
