---

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
    scope: "{{ k3s_systemd_context }}"
  become: "{{ k3s_become_for_systemd | ternary(true, false, k3s_become_for_all) }}"

- name: restart k3s
  ansible.builtin.systemd:
    name: k3s
    state: restarted
    scope: "{{ k3s_systemd_context }}"
    enabled: "{{ k3s_start_on_boot }}"
  retries: 3
  delay: 3
  register: k3s_systemd_restart_k3s
  failed_when:
    - k3s_systemd_restart_k3s is not success
    - not ansible_check_mode
  become: "{{ k3s_become_for_systemd | ternary(true, false, k3s_become_for_all) }}"

- name: restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true
  register: k3s_systemd_restart_docker
  failed_when:
    - k3s_systemd_restart_docker is not success
    - not ansible_check_mode
  become: "{{ k3s_become_for_systemd | ternary(true, false, k3s_become_for_all) }}"

- name: import extra images
  ansible.builtin.command:
    cmd: "{{ k3s_install_dir }}/k3s ctr images import {{ k3s_agent_images_dir }}/{{ item }}"
  loop: "{{ k3s_air_gap_extra_images }}"
  become: "{{ k3s_become_for_install_dir | ternary(true, false, k3s_become_for_all)  }}"
